name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Run benchmark
      run: dotnet run --project source\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark.csproj -c Release --filter * --job Dry

    #- name: Copy results
    #  run: Copy-Item -Path "BenchmarkDotNet.Artifacts\results\*.md" -Destination "results" -Force
      
    #- name: Commit results
    #  run: |
    #    git config --local user.email "$(git log --format='%ae' HEAD^!)"
    #    git config --local user.name "$(git log --format='%an' HEAD^!)"
    #    git add .
    #    git commit -m "Updated results"
    #    git push