name: pull request

on:
  pull_request:
    paths:
      - 'source/**'

jobs:
  pull_request:
    runs-on: windows-latest
    if: "contains('true', 'false')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
        
    - name: Create build dir
      run: New-Item -Path ".\" -Name "build" -ItemType "directory"

    - name: Run benchmark
      run: dotnet run --project ..\source\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark.csproj -c Release --filter * --job Dry
      working-directory: build